language: java
jdk: oraclejdk7
before_install:
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq libstdc++6:i386 lib32z1; fi
  - wget -O android-sdk.tgz http://dl.google.com/android/android-sdk_r22.0.4-linux.tgz
  - tar xzf android-sdk.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

  # Install required components.
  # For a full list, run `android list sdk -a --extended`
  # Note that sysimg-16 downloads the ARM, x86 and MIPS images (we should optimize this).
  # Note that `echo y` only accepts the first license. This is actually convenient, since
  # it prevents the installation of the ATOM and MIPS emulator images. It might cause
  # issues in the future though.
  - echo y | android update sdk --filter platform-tools,build-tools-18.0.1,android-17,extra-android-support,$ANDROID_SDKS --no-ui --force > /dev/null

  - git clone git://github.com/mosabua/maven-android-sdk-deployer.git
  - cd ./maven-android-sdk-deployer
  - mvn install -P4.2
#  # Create and start emulator
#  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
#  - emulator -avd test -no-skin -no-audio -no-window &
#
#before_script:
#  - ./wait_for_emulator

#script: mvn install -Pintegration-tests -Dandroid.device=test
script: mvn install